import { db } from "@/lib/db";
import bcrypt from "bcryptjs";

async function seed() {
  // Seed categories
  const categories = await Promise.all([
    db.category.upsert({
      where: { slug: "instrumentos" },
      update: {},
      create: {
        name: "Instrumentos",
        slug: "instrumentos",
        description: "Instrumentos de precisión para podología profesional",
        image: "/categories/instrumentos.jpg",
        icon: "wrench",
        order: 1,
      },
    }),
    db.category.upsert({
      where: { slug: "insumos" },
      update: {},
      create: {
        name: "Insumos",
        slug: "insumos",
        description: "Insumos desechables y material de uso clínico",
        image: "/categories/insumos.jpg",
        icon: "package",
        order: 2,
      },
    }),
    db.category.upsert({
      where: { slug: "equipamiento" },
      update: {},
      create: {
        name: "Equipamiento",
        slug: "equipamiento",
        description: "Equipos y mobiliario para consultorio podológico",
        image: "/categories/equipamiento.jpg",
        icon: "monitor",
        order: 3,
      },
    }),
    db.category.upsert({
      where: { slug: "cuidado-pies" },
      update: {},
      create: {
        name: "Cuidado de Pies",
        slug: "cuidado-pies",
        description: "Productos para el cuidado y tratamiento de pies",
        image: "/categories/cuidado.jpg",
        icon: "heart",
        order: 4,
      },
    }),
  ]);

  // Seed products
  const products = [
    {
      name: "Pinza de Corte Recto Premium",
      slug: "pinza-corte-recto-premium",
      description: "Pinza de corte recto de acero inoxidable quirúrgico, ideal para procedimientos de podología profesional.",
      content: "<h3>Características</h3><ul><li>Acero inoxidable quirúrgico AISI 420</li><li>Punta recta de corte preciso</li><li>Empuñadura ergonómica con textura antideslizante</li><li>Autoclavable a 134°C</li><li>Longitud: 14 cm</li></ul><h3>Indicaciones</h3><p>Ideal para corte de uñas, hiperqueratosis y onicogrifosis. Uso profesional en consultorio.</p>",
      price: 890,
      comparePrice: 1150,
      sku: "CEN-INS-001",
      stock: 25,
      images: JSON.stringify(["/products/pinza-1.jpg", "/products/pinza-2.jpg"]),
      categoryId: categories[0].id,
      tags: JSON.stringify(["pinza", "corte", "instrumento", "acero inoxidable"]),
      rating: 4.8,
      reviewCount: 124,
      usage: "profesional",
      featured: true,
      professional: true,
    },
    {
      name: "Lima Podológica Doble Grano",
      slug: "lima-podologica-doble-grano",
      description: "Lima profesional de doble grano para tratamiento de hiperqueratosis y uñas engrosadas.",
      content: "<h3>Características</h3><ul><li>Doble grano: grueso (80) y fino (120)</li><li>Material: carburo de tungsteno</li><li>Empuñadura con grip siliconado</li><li>Lavable y desinfectable</li><li>Longitud: 18 cm</li></ul>",
      price: 450,
      sku: "CEN-INS-002",
      stock: 40,
      images: JSON.stringify(["/products/lima-1.jpg", "/products/lima-2.jpg"]),
      categoryId: categories[0].id,
      tags: JSON.stringify(["lima", "podológica", "hiperqueratosis", "uña engrosada"]),
      rating: 4.6,
      reviewCount: 89,
      usage: "profesional",
      featured: true,
      professional: true,
    },
    {
      name: "Gel Desinfectante Clínico 500ml",
      slug: "gel-desinfectante-clinico-500ml",
      description: "Gel desinfectante de uso clínico con acción bactericida, virucida y fungicida.",
      content: "<h3>Características</h3><ul><li>Alcohol etílico al 70%</li><li>Acción bactericida, virucida y fungicida</li><li>Con glicerina hidratante</li><li>Presentación: 500ml con dosificador</li><li>Norma NOM-004-SSA3-2012</li></ul>",
      price: 285,
      sku: "CEN-INS-003",
      stock: 100,
      images: JSON.stringify(["/products/gel-1.jpg"]),
      categoryId: categories[1].id,
      tags: JSON.stringify(["desinfectante", "gel", "higiene", "clínico"]),
      rating: 4.5,
      reviewCount: 67,
      usage: "general",
      featured: true,
    },
    {
      name: "Mesa Podológica Auxiliar",
      slug: "mesa-podologica-auxiliar",
      description: "Mesa auxiliar de acero inoxidable con ruedas para consultorio podológico.",
      content: "<h3>Características</h3><ul><li>Acero inoxidable AISI 304</li><li>Superficie de trabajo: 60 x 40 cm</li><li>Altura regulable: 70-90 cm</li><li>4 ruedas con freno</li><li>Bandeja inferior portaobjetos</li><li>Capacidad de carga: 20 kg</li></ul>",
      price: 4500,
      comparePrice: 5200,
      sku: "CEN-EQP-001",
      stock: 8,
      lowStock: 3,
      images: JSON.stringify(["/products/mesa-1.jpg", "/products/mesa-2.jpg", "/products/mesa-3.jpg"]),
      categoryId: categories[2].id,
      tags: JSON.stringify(["mesa", "auxiliar", "acero inoxidable", "consultorio"]),
      rating: 4.9,
      reviewCount: 45,
      usage: "profesional",
      featured: true,
      professional: true,
    },
    {
      name: "Crema Hidratante Podológica 250ml",
      slug: "crema-hidratante-podologica-250ml",
      description: "Crema hidratante profesional con urea al 10% para tratamiento de piel seca y agrietada.",
      content: "<h3>Características</h3><ul><li>Urea al 10%</li><li>Ácido láctico y glicerina</li><li>Sin parabenos</li><li>Presentación: 250ml</li><li>Dermatológicamente testado</li></ul><h3>Indicaciones</h3><p>Xerosis, hiperqueratosis, piel agrietada de pies.</p>",
      price: 380,
      comparePrice: 450,
      sku: "CEN-CUI-001",
      stock: 60,
      images: JSON.stringify(["/products/crema-1.jpg", "/products/crema-2.jpg"]),
      categoryId: categories[3].id,
      tags: JSON.stringify(["crema", "hidratante", "urea", "piel seca"]),
      rating: 4.7,
      reviewCount: 156,
      usage: "general",
      featured: true,
    },
    {
      name: "Tijera Curva Podológica",
      slug: "tijera-curva-podologica",
      description: "Tijera curva de acero inoxidable para corte preciso de tejidos y vendajes.",
      content: "<h3>Características</h3><ul><li>Acero inoxidable quirúrgico AISI 420</li><li>Punta curva</li><li>Resorte integrado</li><li>Autoclavable</li><li>Longitud: 11.5 cm</li></ul>",
      price: 650,
      sku: "CEN-INS-004",
      stock: 30,
      images: JSON.stringify(["/products/tijera-1.jpg"]),
      categoryId: categories[0].id,
      tags: JSON.stringify(["tijera", "curva", "instrumento", "quirúrgico"]),
      rating: 4.4,
      reviewCount: 72,
      usage: "profesional",
      featured: false,
      professional: true,
    },
    {
      name: "Kit de Bisturíes Desechables (10pz)",
      slug: "kit-bisturis-desechables",
      description: "Kit de 10 bisturíes desechables con mango plástico y hoja de acero inoxidable.",
      content: "<h3>Características</h3><ul><li>10 bisturíes por paquete</li><li>Mango plástico ergonómico</li><li>Hoja de acero inoxidable #11</li><li>Estéril individual</li><li>Uso único</li></ul>",
      price: 195,
      sku: "CEN-INS-005",
      stock: 200,
      images: JSON.stringify(["/products/bisturi-1.jpg"]),
      categoryId: categories[1].id,
      tags: JSON.stringify(["bisturí", "desechable", "estéril", "kit"]),
      rating: 4.3,
      reviewCount: 54,
      usage: "profesional",
      featured: false,
      professional: true,
    },
    {
      name: "Lámpara de Luz Fría LED",
      slug: "lampara-luz-fria-led",
      description: "Lámpara de luz fría LED con brazo articulado para iluminación del área de trabajo.",
      content: "<h3>Características</h3><ul><li>LED de 8W (equivalente a 60W)</li><li>Luz fría 6000K</li><li>Brazo articulado de 90 cm</li><li>Base con pinza o de mesa</li><li>Regulador de intensidad</li></ul>",
      price: 2890,
      comparePrice: 3400,
      sku: "CEN-EQP-002",
      stock: 12,
      images: JSON.stringify(["/products/lampara-1.jpg", "/products/lampara-2.jpg"]),
      categoryId: categories[2].id,
      tags: JSON.stringify(["lámpara", "LED", "luz fría", "iluminación"]),
      rating: 4.8,
      reviewCount: 38,
      usage: "profesional",
      featured: false,
      professional: true,
    },
    {
      name: "Talco Antifúngico Podológico",
      slug: "talco-antifungico-podologico",
      description: "Talco antimicótico profesional para prevención y tratamiento de pieles con tendencia a micosis.",
      content: "<h3>Características</h3><ul><li>Clotrimazol al 1%</li><li>Óxido de zinc</li><li>Presentación: 150g</li><li>Absorbe humedad</li><li>Prevención de pie de atleta</li></ul>",
      price: 220,
      sku: "CEN-CUI-002",
      stock: 80,
      images: JSON.stringify(["/products/talco-1.jpg"]),
      categoryId: categories[3].id,
      tags: JSON.stringify(["talco", "antifúngico", "micosis", "pie de atleta"]),
      rating: 4.5,
      reviewCount: 93,
      usage: "general",
      featured: false,
    },
    {
      name: "Sillón Podológico Hidráulico",
      slug: "sillon-podologico-hidraulico",
      description: "Sillón podológico profesional con elevación hidráulica y reposabrazos ajustables.",
      content: "<h3>Características</h3><ul><li>Elevación hidráulica</li><li>Reposabrazos ajustables 360°</li><li>Respaldo reclinable</li><li>Tapizado en skai lavable</li><li>Base de acero cromado</li><li>Capacidad: 150 kg</li></ul>",
      price: 12500,
      comparePrice: 14500,
      sku: "CEN-EQP-003",
      stock: 4,
      lowStock: 2,
      images: JSON.stringify(["/products/sillon-1.jpg", "/products/sillon-2.jpg", "/products/sillon-3.jpg", "/products/sillon-4.jpg"]),
      categoryId: categories[2].id,
      tags: JSON.stringify(["sillón", "hidráulico", "consultorio", "mobiliario"]),
      rating: 4.9,
      reviewCount: 28,
      usage: "profesional",
      featured: true,
      professional: true,
    },
    {
      name: "Set de Fresas para Micromotor (6pz)",
      slug: "set-fresas-micromotor",
      description: "Set de 6 fresas de carburo de tungsteno para micromotor podológico.",
      content: "<h3>Características</h3><ul><li>6 fresas de carburo de tungsteno</li><li>Diferentes formas: cilíndrica, cónica, esférica</li><li>Compatible con micromotores estándar</li><li>Autoclavables</li><li>Estuche de aluminio</li></ul>",
      price: 780,
      sku: "CEN-INS-006",
      stock: 35,
      images: JSON.stringify(["/products/fresas-1.jpg"]),
      categoryId: categories[0].id,
      tags: JSON.stringify(["fresas", "micromotor", "carburo", "tungsteno"]),
      rating: 4.6,
      reviewCount: 62,
      usage: "profesional",
      featured: false,
      professional: true,
    },
    {
      name: "Espátula Doble Podológica",
      slug: "espatula-doble-podologica",
      description: "Espátula de doble extremo para eliminación de callosidades y limpieza de surcos ungueales.",
      content: "<h3>Características</h3><ul><li>Acero inoxidable quirúrgico</li><li>Doble extremo: espátula y cureta</li><li>Empuñadura serrada</li><li>Autoclavable a 134°C</li><li>Longitud: 16 cm</li></ul>",
      price: 520,
      sku: "CEN-INS-007",
      stock: 45,
      images: JSON.stringify(["/products/espatula-1.jpg"]),
      categoryId: categories[0].id,
      tags: JSON.stringify(["espátula", "cureta", "callosidades", "surco ungueal"]),
      rating: 4.5,
      reviewCount: 48,
      usage: "profesional",
      featured: false,
      professional: true,
    },
    {
      name: "Guantes Nitrilo M (100pz)",
      slug: "guantes-nitrilo-m-100pz",
      description: "Guantes de nitrilo sin polvo, caja de 100 piezas, talla mediana.",
      content: "<h3>Características</h3><ul><li>Nitrilo sin polvo</li><li>Talla M</li><li>100 unidades por caja</li><li>Ambidiestros</li><li>Resistentes a químicos</li><li>Textura en puntas de los dedos</li></ul>",
      price: 320,
      comparePrice: 380,
      sku: "CEN-INS-008",
      stock: 150,
      images: JSON.stringify(["/products/guantes-1.jpg"]),
      categoryId: categories[1].id,
      tags: JSON.stringify(["guantes", "nitrilo", "desechable", "protección"]),
      rating: 4.7,
      reviewCount: 201,
      usage: "general",
      featured: false,
    },
    {
      name: "Aceite Esencial de Árbol de Té 30ml",
      slug: "aceite-esencial-arbol-te",
      description: "Aceite esencial puro de Melaleuca alternifolia con propiedades antimicóticas y antisépticas.",
      content: "<h3>Características</h3><ul><li>100% puro Melaleuca alternifolia</li><li>30ml con gotero</li><li>Propiedades antimicóticas</li><li>Propiedades antisépticas</li><li>Certificado de pureza</li></ul>",
      price: 275,
      sku: "CEN-CUI-003",
      stock: 55,
      images: JSON.stringify(["/products/aceite-1.jpg"]),
      categoryId: categories[3].id,
      tags: JSON.stringify(["aceite", "árbol de té", "antimicótico", "antiséptico"]),
      rating: 4.6,
      reviewCount: 87,
      usage: "general",
      featured: false,
    },
    {
      name: "Micromotor Podológico 35K RPM",
      slug: "micromotor-podologico-35k",
      description: "Micromotor profesional de 35,000 RPM con pedal y mango ergonómico para procedimientos podológicos.",
      content: "<h3>Características</h3><ul><li>35,000 RPM velocidad máxima</li><li>Control de velocidad con pedal</li><li>Mango ergonómico ligero</li><li>Rotación derecha/izquierda</li><li>Incluye set de 6 fresas</li><li>Garantía de 1 año</li></ul>",
      price: 5800,
      comparePrice: 6900,
      sku: "CEN-EQP-004",
      stock: 6,
      lowStock: 3,
      images: JSON.stringify(["/products/micromotor-1.jpg", "/products/micromotor-2.jpg"]),
      categoryId: categories[2].id,
      tags: JSON.stringify(["micromotor", "fresas", "35K RPM", "equipo"]),
      rating: 4.8,
      reviewCount: 52,
      usage: "profesional",
      featured: true,
      professional: true,
    },
    {
      name: "Venda Elástica 10cm x 4.5m",
      slug: "venda-elastica-10cm",
      description: "Venda elástica de alta calidad para vendajes funcionales y compresivos en podología.",
      content: "<h3>Características</h3><ul><li>Ancho: 10 cm</li><li>Largo: 4.5 m</li><li>Alta elasticidad</li><li>Autoadherente</li><li>Hipoalergénica</li><li>Color: beige</li></ul>",
      price: 85,
      sku: "CEN-INS-009",
      stock: 300,
      images: JSON.stringify(["/products/venda-1.jpg"]),
      categoryId: categories[1].id,
      tags: JSON.stringify(["venda", "elástica", "vendaje", "compresivo"]),
      rating: 4.4,
      reviewCount: 134,
      usage: "general",
      featured: false,
    },
  ];

  for (const product of products) {
    await db.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });
  }

  // Create admin user with hashed password
  const adminPassword = await bcrypt.hash("cenpod2024", 12);
  await db.user.upsert({
    where: { email: "admin@cenpod.mx" },
    update: {},
    create: {
      email: "admin@cenpod.mx",
      name: "Admin CENPOD",
      password: adminPassword,
      role: "admin",
    },
  });

  console.log("Seed completed successfully!");
  console.log(`Categories: ${categories.length}`);
  console.log(`Products: ${products.length}`);
}

seed().catch(console.error);
